return {
  "folke/snacks.nvim",
  priority = 1000,
  lazy = false,
  opts = {
    picker = { enabled = true },
    explorer = { enabled = true },
    lazygit = { enabled = true },
    dashboard = { enabled = true },
    notifier = { enabled = true, timeout = 3000 },
    terminal = { enabled = true },
    bigfile = { enabled = true },
    quickfile = { enabled = true },
    input = { enabled = true },
  },
  keys = {
    { "<leader>ff", function() Snacks.picker.files() end, desc = "Find files" },
    { "<leader>fg", function() Snacks.picker.grep() end, desc = "Live grep" },
    { "<leader>fb", function() Snacks.picker.buffers() end, desc = "Buffers" },
    { "<leader>fh", function() Snacks.picker.help() end, desc = "Help tags" },
    { "<leader>fr", function() Snacks.picker.recent() end, desc = "Recent files" },
    { "<leader>fc", function() Snacks.picker.commands() end, desc = "Commands" },
    { "<leader>fk", function() Snacks.picker.keymaps() end, desc = "Keymaps" },
    { "<leader>fd", function() Snacks.picker.diagnostics() end, desc = "Diagnostics" },
    { "<leader>fs", function() Snacks.picker.lsp_symbols() end, desc = "Document symbols" },
    { "<leader>fS", function() Snacks.picker.lsp_workspace_symbols() end, desc = "Workspace symbols" },
    { "<leader>f/", function() Snacks.picker.lines() end, desc = "Search buffer" },
    { '<leader>f"', function() Snacks.picker.registers() end, desc = "Registers" },
    { "<leader>fR", function() Snacks.picker.resume() end, desc = "Resume last picker" },
    { "<leader>e",  function() Snacks.explorer() end, desc = "Explorer (cwd)" },
    { "<leader>E",  function() Snacks.explorer({ cwd = vim.fn.expand("%:p:h") }) end, desc = "Explorer (file dir)" },
    { "<leader>gg", function() Snacks.lazygit() end, desc = "Lazygit" },
    { "<leader>gl", function() Snacks.lazygit.log() end, desc = "Lazygit log" },
    { "<leader>gf", function() Snacks.lazygit.log_file() end, desc = "Lazygit file history" },
    { "<leader>go", function() Snacks.gitbrowse() end, desc = "Git browse (open in browser)" },
    { "<leader>tt", function() Snacks.terminal() end, desc = "Toggle terminal" },
    { "<leader>n",  function() Snacks.notifier.show_history() end, desc = "Notification history" },
  },
}
